#!/usr/bin/env bash
# configure.sh — interactive generator for sanitizer.config.
#
# Prompts for region, target buckets, naming, and runtime tuning, then writes a
# ready-to-use `sanitizer.config` that deploy.sh consumes. Existing values (from
# a previous config or the example) are offered as defaults — press Enter to keep
# them.
#
# Usage:
#   ./configure.sh                 # writes ./sanitizer.config
#   ./configure.sh -o my.config    # writes a custom path

set -euo pipefail

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
prompt()  { echo -ne "${CYAN}$*${NC}"; }
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="$SCRIPT_DIR/sanitizer.config"

while [[ $# -gt 0 ]]; do
  case $1 in
    -o|--output) OUTPUT="$2"; shift 2 ;;
    -h|--help)
      sed -n '/^# Usage/,/^set -/p' "$0" | grep '^#' | sed 's/^# \?//'
      exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Seed defaults ──────────────────────────────────────────────────────────────
# Pull starting values from an existing config, else the example, else built-ins.
REGION="ap-south-1"
BUCKETS=""
FUNCTION_NAME="s3-file-sanitizer"
LAYER_NAME="s3-file-sanitizer-deps"
PREFIX=""
MEMORY=512
TIMEOUT=60
RUNTIME="python3.11"
MAX_FILE_SIZE_MB=50
MAX_IMAGE_DIMENSION=4096

SEED=""
if [[ -f "$OUTPUT" ]]; then
  SEED="$OUTPUT"
elif [[ -f "$SCRIPT_DIR/sanitizer.config.example" ]]; then
  SEED="$SCRIPT_DIR/sanitizer.config.example"
fi
if [[ -n "$SEED" ]]; then
  # shellcheck source=/dev/null
  source "$SEED"
  info "Seeded defaults from: $SEED"
fi

echo -e "\n${BOLD}S3 File Sanitizer — configuration${NC}"
echo "Press Enter to accept the [default] shown for each prompt.\n"

# ask VAR "Question" "default"
ask() {
  local __var="$1" __question="$2" __default="$3" __answer
  prompt "$__question [${__default}]: "
  read -r __answer
  printf -v "$__var" '%s' "${__answer:-$__default}"
}

ask REGION              "AWS region (Lambda + all buckets live here)" "$REGION"

echo
echo "Enter the S3 bucket name(s) to attach the sanitizer to."
echo "Separate multiple buckets with spaces. All must be in ${REGION}."
ask BUCKETS             "Bucket name(s)" "$BUCKETS"
while [[ -z "${BUCKETS// /}" ]]; do
  warn "At least one bucket is required."
  ask BUCKETS           "Bucket name(s)" "$BUCKETS"
done

echo
ask FUNCTION_NAME       "Lambda function name" "$FUNCTION_NAME"
ask LAYER_NAME          "Dependency layer name" "$LAYER_NAME"

echo
echo "Optional: restrict the trigger to keys under a prefix (e.g. 'uploads/')."
echo "Leave blank to sanitize every object created in the bucket."
ask PREFIX              "Key prefix" "$PREFIX"

echo
ask MEMORY              "Lambda memory (MB)" "$MEMORY"
ask TIMEOUT             "Lambda timeout (seconds)" "$TIMEOUT"
ask RUNTIME             "Python runtime" "$RUNTIME"

echo
ask MAX_FILE_SIZE_MB    "Max file size to process (MB)" "$MAX_FILE_SIZE_MB"
ask MAX_IMAGE_DIMENSION "Max image dimension (px)" "$MAX_IMAGE_DIMENSION"

# ── Write the config ───────────────────────────────────────────────────────────
cat > "$OUTPUT" <<EOF
# sanitizer.config — generated by configure.sh
# Edit by hand or re-run ./configure.sh to regenerate.

# AWS region (Lambda + all target buckets).
REGION="${REGION}"

# Space-separated list of S3 bucket names. All must be in REGION.
BUCKETS="${BUCKETS}"

# Naming.
FUNCTION_NAME="${FUNCTION_NAME}"
LAYER_NAME="${LAYER_NAME}"

# Restrict the trigger to keys under this prefix (empty = whole bucket).
PREFIX="${PREFIX}"

# Lambda runtime tuning.
MEMORY=${MEMORY}
TIMEOUT=${TIMEOUT}
RUNTIME="${RUNTIME}"

# Sanitizer limits (passed to the function as environment variables).
MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB}
MAX_IMAGE_DIMENSION=${MAX_IMAGE_DIMENSION}
EOF

echo
info "Wrote configuration to: ${OUTPUT}"
echo
echo -e "${BOLD}Summary${NC}"
echo "  Region:    ${REGION}"
echo "  Buckets:   ${BUCKETS}"
echo "  Function:  ${FUNCTION_NAME}"
echo "  Layer:     ${LAYER_NAME}"
echo "  Prefix:    ${PREFIX:-<all objects>}"
echo "  Memory:    ${MEMORY} MB / Timeout: ${TIMEOUT}s / Runtime: ${RUNTIME}"
echo "  Limits:    ${MAX_FILE_SIZE_MB} MB max file, ${MAX_IMAGE_DIMENSION}px max image"
echo
echo "Next: review the file, then deploy with:"
echo "  ./deploy.sh --config ${OUTPUT}"
