#!/usr/bin/env bash
# deploy.sh — Deploy the S3 file sanitizer Lambda, its dependency layer, the IAM
# execution role, and the S3 ObjectCreated triggers for one or more buckets.
#
# Configuration is read from a sourceable config file (default ./sanitizer.config,
# generated by ./configure.sh). Any value can be overridden on the command line.
#
# Usage:
#   ./deploy.sh [--config FILE] [options]
#
# Options:
#   --config FILE       Config file to source (default: ./sanitizer.config)
#   --region REGION     AWS region (overrides config)
#   --bucket BUCKET     Target bucket; repeatable. Overrides BUCKETS from config.
#   --function NAME     Lambda function name (overrides config)
#   --layer NAME        Dependency layer name (overrides config)
#   --prefix PREFIX     Restrict trigger to keys under this prefix
#   --skip-layer        Reuse the existing layer (use when only lambda_function.py changed)
#   --skip-trigger      Skip S3 event-notification setup
#   --help              Show this message
#
# Examples:
#   First deployment from config:
#     ./configure.sh && ./deploy.sh
#
#   Code-only update (layer + triggers unchanged):
#     ./deploy.sh --skip-layer --skip-trigger
#
#   One-off without a config file:
#     ./deploy.sh --region us-east-1 --bucket my-bucket --function my-sanitizer

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
section() { echo -e "\n${BOLD}── $* ──${NC}"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Defaults (overridden by config, then by flags) ─────────────────────────────
CONFIG_FILE="$SCRIPT_DIR/sanitizer.config"
REGION="ap-south-1"
RUNTIME="python3.11"
HANDLER="lambda_function.lambda_handler"
MEMORY=512
TIMEOUT=60
FUNCTION_NAME="s3-file-sanitizer"
LAYER_NAME="s3-file-sanitizer-deps"
PREFIX=""
BUCKETS=""
MAX_FILE_SIZE_MB=50
MAX_IMAGE_DIMENSION=4096
SKIP_LAYER=false
SKIP_TRIGGER=false

# CLI buckets accumulate separately so flags can override (not append to) config.
CLI_BUCKETS=()
CLI_REGION=""; CLI_FUNCTION=""; CLI_LAYER=""; CLI_PREFIX=""; CLI_PREFIX_SET=false

# ── First pass: find --config so it can be sourced before other flags apply ────
ARGS=("$@")
for ((i=0; i<${#ARGS[@]}; i++)); do
  if [[ "${ARGS[$i]}" == "--config" ]]; then
    CONFIG_FILE="${ARGS[$((i+1))]:-}"
    [[ -z "$CONFIG_FILE" ]] && error "--config requires a path."
  fi
done

if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$CONFIG_FILE"
  info "Loaded config: $CONFIG_FILE"
else
  warn "No config file at $CONFIG_FILE — relying on flags and defaults."
fi

# ── Argument parsing (flags override config) ───────────────────────────────────
while [[ $# -gt 0 ]]; do
  case $1 in
    --config)       shift 2 ;;  # already handled
    --region)       CLI_REGION="$2";        shift 2 ;;
    --bucket)       CLI_BUCKETS+=("$2");     shift 2 ;;
    --function)     CLI_FUNCTION="$2";       shift 2 ;;
    --layer)        CLI_LAYER="$2";          shift 2 ;;
    --prefix)       CLI_PREFIX="$2"; CLI_PREFIX_SET=true; shift 2 ;;
    --skip-layer)   SKIP_LAYER=true;         shift   ;;
    --skip-trigger) SKIP_TRIGGER=true;       shift   ;;
    --help)
      sed -n '/^# Usage/,/^set -/p' "$0" | grep '^#' | sed 's/^# \?//'
      exit 0 ;;
    *) error "Unknown option: $1. Run with --help for usage." ;;
  esac
done

[[ -n "$CLI_REGION"   ]] && REGION="$CLI_REGION"
[[ -n "$CLI_FUNCTION" ]] && FUNCTION_NAME="$CLI_FUNCTION"
[[ -n "$CLI_LAYER"    ]] && LAYER_NAME="$CLI_LAYER"
[[ "$CLI_PREFIX_SET" == true ]] && PREFIX="$CLI_PREFIX"
[[ ${#CLI_BUCKETS[@]} -gt 0 ]] && BUCKETS="${CLI_BUCKETS[*]}"

# ── Validate ───────────────────────────────────────────────────────────────────
[[ -z "${BUCKETS// /}" ]] && error "No buckets configured. Set BUCKETS in $CONFIG_FILE or pass --bucket."
read -ra BUCKET_LIST <<< "$BUCKETS"

# ── Resolve paths ─────────────────────────────────────────────────────────────
BUILD_DIR="$SCRIPT_DIR/.build"
LAYER_ZIP="$BUILD_DIR/sanitizer-deps.zip"
FUNCTION_ZIP="$BUILD_DIR/sanitizer-function.zip"

# ── Preflight checks ──────────────────────────────────────────────────────────
section "Preflight"

command -v aws     &>/dev/null || error "AWS CLI not found. Install from https://aws.amazon.com/cli/"
command -v python3 &>/dev/null || error "python3 not found."
command -v pip3    &>/dev/null || error "pip3 not found."
command -v zip     &>/dev/null || error "zip not found."

info "AWS CLI:   $(aws --version 2>&1 | head -1)"
info "Python:    $(python3 --version)"
info "Region:    $REGION"
info "Buckets:   ${BUCKET_LIST[*]}"
info "Function:  $FUNCTION_NAME"
info "Layer:     $LAYER_NAME"
info "Prefix:    ${PREFIX:-<all objects>}"

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text --region "$REGION" 2>/dev/null) \
  || error "AWS credentials not configured or invalid. Run 'aws configure'."
info "Account:   $ACCOUNT_ID"

FUNCTION_ARN="arn:aws:lambda:$REGION:$ACCOUNT_ID:function:$FUNCTION_NAME"

mkdir -p "$BUILD_DIR"

# ── IAM role ──────────────────────────────────────────────────────────────────
section "IAM Role"

ROLE_NAME="${FUNCTION_NAME}-role"
ROLE_ARN="arn:aws:iam::$ACCOUNT_ID:role/$ROLE_NAME"

if aws iam get-role --role-name "$ROLE_NAME" &>/dev/null; then
  info "Role already exists: $ROLE_ARN"
else
  info "Creating IAM role: $ROLE_NAME"
  aws iam create-role \
    --role-name "$ROLE_NAME" \
    --assume-role-policy-document '{
      "Version": "2012-10-17",
      "Statement": [{
        "Effect": "Allow",
        "Principal": {"Service": "lambda.amazonaws.com"},
        "Action": "sts:AssumeRole"
      }]
    }' \
    --region "$REGION" \
    --output text --query 'Role.RoleId' >/dev/null
  info "Role created"
fi

# CloudWatch Logs — always ensure attached (idempotent)
aws iam attach-role-policy \
  --role-name "$ROLE_NAME" \
  --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole \
  2>/dev/null || true
info "AWSLambdaBasicExecutionRole attached"

# Build S3 resource ARN lists across all buckets.
OBJECT_RESOURCES=""; BUCKET_RESOURCES=""
for b in "${BUCKET_LIST[@]}"; do
  OBJECT_RESOURCES+="\"arn:aws:s3:::${b}/*\","
  BUCKET_RESOURCES+="\"arn:aws:s3:::${b}\","
done
OBJECT_RESOURCES="${OBJECT_RESOURCES%,}"
BUCKET_RESOURCES="${BUCKET_RESOURCES%,}"

info "Applying S3 access policy to role (${#BUCKET_LIST[@]} bucket(s))"
aws iam put-role-policy \
  --role-name "$ROLE_NAME" \
  --policy-name "${FUNCTION_NAME}-s3-access" \
  --policy-document "{
    \"Version\": \"2012-10-17\",
    \"Statement\": [{
      \"Effect\": \"Allow\",
      \"Action\": [\"s3:GetObject\", \"s3:PutObject\", \"s3:DeleteObject\"],
      \"Resource\": [${OBJECT_RESOURCES}]
    }, {
      \"Effect\": \"Allow\",
      \"Action\": [\"s3:ListBucket\"],
      \"Resource\": [${BUCKET_RESOURCES}]
    }]
  }"
info "S3 policy applied"

# IAM changes can take a few seconds to propagate
sleep 5

# ── Dependency layer ──────────────────────────────────────────────────────────
if [[ "$SKIP_LAYER" == true ]]; then
  info "Skipping layer build (--skip-layer)"
  LAYER_ARN=$(aws lambda list-layer-versions \
    --layer-name "$LAYER_NAME" \
    --region "$REGION" \
    --query 'LayerVersions[0].LayerVersionArn' \
    --output text) || error "No existing layer found. Remove --skip-layer to build one."
  [[ "$LAYER_ARN" == "None" ]] && error "No existing layer versions found. Remove --skip-layer."
  info "Using existing layer: $LAYER_ARN"
else
  section "Dependency Layer"

  LAYER_BUILD="$BUILD_DIR/layer"
  rm -rf "$LAYER_BUILD"
  mkdir -p "$LAYER_BUILD/python"

  PY_VERSION="${RUNTIME#python}"
  info "Installing Python dependencies (linux/x86_64 wheels for $RUNTIME)"
  pip3 install \
    --quiet \
    --platform manylinux2014_x86_64 \
    --implementation cp \
    --python-version "$PY_VERSION" \
    --only-binary=:all: \
    --requirement "$SCRIPT_DIR/requirements.txt" \
    --target "$LAYER_BUILD/python"

  info "Packaging layer"
  (cd "$LAYER_BUILD" && zip -qr "$LAYER_ZIP" .)
  info "Layer package: $LAYER_ZIP ($(du -sh "$LAYER_ZIP" | cut -f1))"

  info "Publishing layer: $LAYER_NAME"
  LAYER_ARN=$(aws lambda publish-layer-version \
    --layer-name "$LAYER_NAME" \
    --zip-file "fileb://$LAYER_ZIP" \
    --compatible-runtimes "$RUNTIME" \
    --region "$REGION" \
    --query 'LayerVersionArn' \
    --output text)
  info "Layer published: $LAYER_ARN"
fi

# ── Function code ─────────────────────────────────────────────────────────────
section "Function Code"

ENV_VARS="Variables={MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB},MAX_IMAGE_DIMENSION=${MAX_IMAGE_DIMENSION}}"

info "Packaging function"
zip -qj "$FUNCTION_ZIP" "$SCRIPT_DIR/lambda_function.py"
info "Function package: $FUNCTION_ZIP ($(du -sh "$FUNCTION_ZIP" | cut -f1))"

if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$REGION" &>/dev/null; then
  info "Updating existing function: $FUNCTION_NAME"
  aws lambda update-function-code \
    --function-name "$FUNCTION_NAME" \
    --zip-file "fileb://$FUNCTION_ZIP" \
    --region "$REGION" \
    --output text --query 'FunctionArn' >/dev/null
  info "Code updated"

  aws lambda wait function-updated --function-name "$FUNCTION_NAME" --region "$REGION"

  aws lambda update-function-configuration \
    --function-name "$FUNCTION_NAME" \
    --handler "$HANDLER" \
    --timeout "$TIMEOUT" \
    --memory-size "$MEMORY" \
    --layers "$LAYER_ARN" \
    --environment "$ENV_VARS" \
    --region "$REGION" \
    --output text --query 'FunctionArn' >/dev/null
  info "Config updated"
else
  info "Creating new function: $FUNCTION_NAME"
  aws lambda create-function \
    --function-name "$FUNCTION_NAME" \
    --runtime "$RUNTIME" \
    --role "$ROLE_ARN" \
    --handler "$HANDLER" \
    --zip-file "fileb://$FUNCTION_ZIP" \
    --timeout "$TIMEOUT" \
    --memory-size "$MEMORY" \
    --layers "$LAYER_ARN" \
    --environment "$ENV_VARS" \
    --region "$REGION" \
    --output text --query 'FunctionArn' >/dev/null
  info "Function created"
  aws lambda wait function-active --function-name "$FUNCTION_NAME" --region "$REGION"
fi

# ── S3 triggers ───────────────────────────────────────────────────────────────
if [[ "$SKIP_TRIGGER" == true ]]; then
  info "Skipping S3 trigger setup (--skip-trigger)"
else
  section "S3 Triggers"

  # Optional prefix filter fragment for the notification config.
  FILTER_JSON=""
  if [[ -n "$PREFIX" ]]; then
    FILTER_JSON=",\"Filter\": {\"Key\": {\"FilterRules\": [{\"Name\": \"prefix\", \"Value\": \"${PREFIX}\"}]}}"
  fi

  for b in "${BUCKET_LIST[@]}"; do
    info "Wiring trigger for bucket: $b"
    BUCKET_ARN="arn:aws:s3:::$b"
    # Deterministic, idempotent statement id per bucket (alnum + hyphen only).
    STMT_ID="s3invoke-$(printf '%s' "$b" | tr -c 'a-zA-Z0-9' '-')"
    STMT_ID="${STMT_ID:0:100}"

    aws lambda remove-permission \
      --function-name "$FUNCTION_NAME" \
      --statement-id "$STMT_ID" \
      --region "$REGION" 2>/dev/null || true

    aws lambda add-permission \
      --function-name "$FUNCTION_NAME" \
      --statement-id "$STMT_ID" \
      --action lambda:InvokeFunction \
      --principal s3.amazonaws.com \
      --source-arn "$BUCKET_ARN" \
      --source-account "$ACCOUNT_ID" \
      --region "$REGION" \
      --output text --query 'Statement' >/dev/null
    info "  Invoke permission granted for $b"

    # NOTE: put-bucket-notification-configuration REPLACES the bucket's entire
    # notification config. If the bucket already has other notifications, see the
    # README ("Caveat: existing bucket notifications") before running this.
    aws s3api put-bucket-notification-configuration \
      --bucket "$b" \
      --region "$REGION" \
      --notification-configuration "{
        \"LambdaFunctionConfigurations\": [{
          \"Id\": \"file-sanitizer-trigger\",
          \"LambdaFunctionArn\": \"$FUNCTION_ARN\",
          \"Events\": [\"s3:ObjectCreated:*\"]${FILTER_JSON}
        }]
      }"
    info "  ObjectCreated notification configured for $b"
  done
fi

# ── Done ──────────────────────────────────────────────────────────────────────
section "Deployment Complete"
echo -e "  ${GREEN}Function ARN:${NC} $FUNCTION_ARN"
echo -e "  ${GREEN}Layer ARN:${NC}    $LAYER_ARN"
for b in "${BUCKET_LIST[@]}"; do
  echo -e "  ${GREEN}Trigger:${NC}      s3://$b/${PREFIX}** → $FUNCTION_NAME"
done
echo ""
info "Verify with:"
echo "  aws s3api head-object --bucket ${BUCKET_LIST[0]} --key <prefix>/<file> --region $REGION --query Metadata"
echo ""
info "Monitor logs:"
echo "  aws logs tail /aws/lambda/$FUNCTION_NAME --follow --region $REGION"
